# -*- coding: utf-8 -*-
"""AI_Image_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mWBRz5RgdLZmc84DUM-XQXmVi4pdFqWr
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U diffusers transformers accelerate

import diffusers
print(diffusers.__version__)

import torch

import gradio as gr

from diffusers import AutoPipelineForText2Image

from huggingface_hub import login
login()

pipe = AutoPipelineForText2Image.from_pretrained(
    "stabilityai/sdxl-turbo",
    torch_dtype=torch.float16,
    device_map="balanced"
)

pipe.enable_attention_slicing()

def generate_image(prompt):
    return pipe(
        prompt,
        num_inference_steps=1,
        guidance_scale=0.0
    ).images[0]

gr.Interface(
    fn=generate_image,
    inputs=gr.Textbox(label="Prompt"),
    outputs=gr.Image(type="pil"),
    title="Fast AI Image Generator (SDXL Turbo)"
).launch()